#!/usr/bin/python

import sys
sys.path.insert(0, '/data/mysqladm2/')
from flask import Flask, g
from flask.ext.script import Manager
from mysqladm.fapp import WrapFlask
import mysqladm.servers
import mysqladm.core

app = WrapFlask(__name__)
manager = Manager(app,with_default_commands=False)

@manager.command
@manager.option('-s', '--server', help='What server to sync from, default all',required=False)
def agentsync(server=''):
	"""
	Compares the list of databases between mysqladm and the mysqlagent and corrects differences
	"""
	g.db = mysqladm.core.db_connect()

	## Load servers
	rows = mysqladm.servers.get_all_servers()
	
	for row in rows:
		print row['hostname']
		
@manager.command
def listservers():
	"""
	List servers managed by mysqladm
	"""
	g.db = mysqladm.core.db_connect()

	## Load servers
	rows = mysqladm.servers.get_all_servers()
	
	for row in rows:
		print row['hostname']
		
@manager.command
def initsetup():
	"""
	Runs the initial setup code to create the database and set up mysqladm
	"""
	print "Function not implemented (yet)"
    
if __name__ == "__main__":
	manager.run()